version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

submodules:
  exclude: all
  recursive: false

sphinx:
  configuration: docs/source/conf.py

formats: [ ]

python:
  install:
    - requirements: docs/requirements.txt
